// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  planId: __t.u32().name("plan_id"),
  proposalId: __t.u32().name("proposal_id"),
  friendId: __t.u32().name("friend_id"),
  acceptedAt: __t.timestamp().name("accepted_at"),
  acceptanceKey: __t.string().name("acceptance_key"),
});
