// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AnswerState,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  planId: __t.u32().name("plan_id"),
  friendId: __t.u32().name("friend_id"),
  activityId: __t.u32().name("activity_id"),
  get state() {
    return AnswerState;
  },
  maxPrice: __t.option(__t.u32()).name("max_price"),
  answerKey: __t.string().name("answer_key"),
});
