// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PrivateRoomChoiceInput,
} from "./types";

export default {
  publicRoomId: __t.string(),
  title: __t.string(),
  creatorDisplayName: __t.string(),
  startsAt: __t.timestamp(),
  endsAt: __t.timestamp(),
  timezone: __t.string(),
  get choices() {
    return __t.array(PrivateRoomChoiceInput);
  },
  inviteToken: __t.string(),
  inviteExpiresAt: __t.option(__t.timestamp()),
  inviteMaxUses: __t.option(__t.u32()),
};
