// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  planId: __t.u32().name("plan_id"),
  proposalId: __t.u32().name("proposal_id"),
  activityId: __t.u32().name("activity_id"),
  sequence: __t.u32(),
  decidedAt: __t.timestamp().name("decided_at"),
  decisionDurationMs: __t.u64().name("decision_duration_ms"),
  eligibleCount: __t.u32().name("eligible_count"),
  acceptedCount: __t.u32().name("accepted_count"),
});
