// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  planId: __t.u32().name("plan_id"),
  kind: __t.string(),
  friendId: __t.option(__t.u32()).name("friend_id"),
  activityId: __t.option(__t.u32()).name("activity_id"),
  message: __t.string(),
  at: __t.timestamp(),
});
