// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  planId: __t.u32().name("plan_id"),
  identity: __t.identity(),
  name: __t.string(),
  online: __t.bool(),
  joinedAt: __t.timestamp().name("joined_at"),
  droppedAt: __t.option(__t.timestamp()).name("dropped_at"),
});
