// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u32().primaryKey().name("room_id"),
  lastBotMessageAt: __t.option(__t.timestamp()).name("last_bot_message_at"),
  botMessagesInCurrentMinute: __t.u32().name("bot_messages_in_current_minute"),
  minuteWindowStartedAt: __t.timestamp().name("minute_window_started_at"),
  lastProcessedMessageId: __t.u64().name("last_processed_message_id"),
});
