// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roomId: __t.u32().primaryKey().name("room_id"),
  decisionCount: __t.u32().name("decision_count"),
  totalDecisionSeconds: __t.u64().name("total_decision_seconds"),
  latestLockedAt: __t.option(__t.timestamp()).name("latest_locked_at"),
});
