// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  acceptanceId: __t.u32().primaryKey().name("acceptance_id"),
  roomId: __t.u32().name("room_id"),
  proposalId: __t.u32().name("proposal_id"),
  memberName: __t.string().name("member_name"),
  acceptedAt: __t.timestamp().name("accepted_at"),
});
