// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ProposalStatus,
} from "./types";


export default __t.row({
  proposalId: __t.u32().primaryKey().name("proposal_id"),
  roomId: __t.u32().name("room_id"),
  choiceId: __t.u32().name("choice_id"),
  proposerName: __t.string().name("proposer_name"),
  get status() {
    return ProposalStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
});
