// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u32().name("room_id"),
  friendId: __t.u32().name("friend_id"),
  friendName: __t.string().name("friend_name"),
  statement: __t.string(),
  category: __t.string(),
  sourceMessageId: __t.u64().name("source_message_id"),
  recordedAt: __t.timestamp().name("recorded_at"),
});
