// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u32().name("room_id"),
  senderIdentity: __t.identity().name("sender_identity"),
  senderName: __t.string().name("sender_name"),
  isBot: __t.bool().name("is_bot"),
  body: __t.string(),
  kind: __t.string(),
  payloadJson: __t.string().name("payload_json"),
  sentAt: __t.timestamp().name("sent_at"),
});
