// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AnswerState,
} from "./types";


export default __t.row({
  voteId: __t.u32().primaryKey().name("vote_id"),
  roomId: __t.u32().name("room_id"),
  choiceId: __t.u32().name("choice_id"),
  memberName: __t.string().name("member_name"),
  get state() {
    return AnswerState;
  },
  maxPrice: __t.option(__t.u32()).name("max_price"),
});
