// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  RoomMembershipRole,
} from "./types";


export default __t.row({
  membershipId: __t.u32().primaryKey().name("membership_id"),
  roomId: __t.u32().name("room_id"),
  displayName: __t.string().name("display_name"),
  joinedAt: __t.timestamp().name("joined_at"),
  get role() {
    return RoomMembershipRole;
  },
});
