// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  choiceId: __t.u32().primaryKey().name("choice_id"),
  roomId: __t.u32().name("room_id"),
  label: __t.string(),
  price: __t.option(__t.u32()),
  minPeople: __t.u32().name("min_people"),
  sortOrder: __t.u32().name("sort_order"),
});
