// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PrivateRoomStatus,
} from "./types";


export default __t.row({
  roomId: __t.u32().primaryKey().name("room_id"),
  publicRoomId: __t.string().name("public_room_id"),
  title: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  get status() {
    return PrivateRoomStatus;
  },
});
