// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  decisionId: __t.u32().primaryKey().name("decision_id"),
  roomId: __t.u32().name("room_id"),
  choiceId: __t.u32().name("choice_id"),
  lockedAt: __t.timestamp().name("locked_at"),
  decisionDurationSeconds: __t.u64().name("decision_duration_seconds"),
  eligibleAcceptanceCount: __t.u32().name("eligible_acceptance_count"),
});
