// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlanStatus,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  shareCode: __t.string().name("share_code"),
  title: __t.string(),
  dateLabel: __t.string().name("date_label"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  closedBy: __t.option(__t.identity()).name("closed_by"),
  closedAt: __t.option(__t.timestamp()).name("closed_at"),
  get status() {
    return PlanStatus;
  },
  lockedActivityId: __t.option(__t.u32()).name("locked_activity_id"),
  version: __t.u64(),
});
