// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ProposalStatus,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  planId: __t.u32().name("plan_id"),
  activityId: __t.u32().name("activity_id"),
  proposedBy: __t.u32().name("proposed_by"),
  get status() {
    return ProposalStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
});
