// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  planId: __t.u32().name("plan_id"),
  decisionsTaken: __t.u32().name("decisions_taken"),
  totalDecisionTimeMs: __t.u64().name("total_decision_time_ms"),
  lastDecisionTimeMs: __t.u64().name("last_decision_time_ms"),
  lastDecidedAt: __t.option(__t.timestamp()).name("last_decided_at"),
});
