// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PrivateRoomStatus,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  title: __t.string(),
  get status() {
    return PrivateRoomStatus;
  },
  choiceLabels: __t.array(__t.string()).name("choice_labels"),
  selectedChoiceLabel: __t.option(__t.string()).name("selected_choice_label"),
  decisionCount: __t.u32().name("decision_count"),
  publishedAt: __t.timestamp().name("published_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  startsAt: __t.option(__t.timestamp()).name("starts_at"),
  timezone: __t.option(__t.string()),
});
