// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Acceptance = __t.object("Acceptance", {
  id: __t.u32(),
  planId: __t.u32(),
  proposalId: __t.u32(),
  friendId: __t.u32(),
  acceptedAt: __t.timestamp(),
  acceptanceKey: __t.string(),
});
export type Acceptance = __Infer<typeof Acceptance>;

export const Activity = __t.object("Activity", {
  id: __t.u32(),
  planId: __t.u32(),
  name: __t.string(),
  price: __t.u32(),
  minPeople: __t.u32(),
  distanceKm: __t.option(__t.u32()),
  timeMinutes: __t.option(__t.u32()),
});
export type Activity = __Infer<typeof Activity>;

export const Answer = __t.object("Answer", {
  id: __t.u32(),
  planId: __t.u32(),
  friendId: __t.u32(),
  activityId: __t.u32(),
  get state() {
    return AnswerState;
  },
  maxPrice: __t.option(__t.u32()),
  answerKey: __t.string(),
});
export type Answer = __Infer<typeof Answer>;

// The tagged union or sum type for the algebraic type `AnswerState`.
export const AnswerState = __t.enum("AnswerState", {
  In: __t.unit(),
  Out: __t.unit(),
  Conditional: __t.unit(),
});
export type AnswerState = __Infer<typeof AnswerState>;

export const BotRoomState = __t.object("BotRoomState", {
  roomId: __t.u32(),
  lastBotMessageAt: __t.option(__t.timestamp()),
  botMessagesInCurrentMinute: __t.u32(),
  minuteWindowStartedAt: __t.timestamp(),
  lastProcessedMessageId: __t.u64(),
});
export type BotRoomState = __Infer<typeof BotRoomState>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  roomId: __t.u32(),
  senderIdentity: __t.identity(),
  senderName: __t.string(),
  isBot: __t.bool(),
  body: __t.string(),
  kind: __t.string(),
  payloadJson: __t.string(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const EventLog = __t.object("EventLog", {
  id: __t.u64(),
  planId: __t.u32(),
  kind: __t.string(),
  friendId: __t.option(__t.u32()),
  activityId: __t.option(__t.u32()),
  message: __t.string(),
  at: __t.timestamp(),
});
export type EventLog = __Infer<typeof EventLog>;

export const Friend = __t.object("Friend", {
  id: __t.u32(),
  planId: __t.u32(),
  identity: __t.identity(),
  friendKey: __t.string(),
  name: __t.string(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
  droppedAt: __t.option(__t.timestamp()),
});
export type Friend = __Infer<typeof Friend>;

export const LocationSubmission = __t.object("LocationSubmission", {
  id: __t.u64(),
  roomId: __t.u32(),
  friendId: __t.u32(),
  lat: __t.f64(),
  lng: __t.f64(),
  submittedAt: __t.timestamp(),
});
export type LocationSubmission = __Infer<typeof LocationSubmission>;

export const MemberPreference = __t.object("MemberPreference", {
  id: __t.u64(),
  roomId: __t.u32(),
  friendId: __t.u32(),
  friendName: __t.string(),
  statement: __t.string(),
  category: __t.string(),
  sourceMessageId: __t.u64(),
  recordedAt: __t.timestamp(),
});
export type MemberPreference = __Infer<typeof MemberPreference>;

export const MyBotRoomState = __t.object("MyBotRoomState", {
  roomId: __t.u32(),
  lastBotMessageAt: __t.option(__t.timestamp()),
  botMessagesInCurrentMinute: __t.u32(),
  minuteWindowStartedAt: __t.timestamp(),
  lastProcessedMessageId: __t.u64(),
});
export type MyBotRoomState = __Infer<typeof MyBotRoomState>;

export const MyRoom = __t.object("MyRoom", {
  roomId: __t.u32(),
  publicRoomId: __t.string(),
  title: __t.string(),
  createdAt: __t.timestamp(),
  get status() {
    return PrivateRoomStatus;
  },
});
export type MyRoom = __Infer<typeof MyRoom>;

export const MyRoomAcceptance = __t.object("MyRoomAcceptance", {
  acceptanceId: __t.u32(),
  roomId: __t.u32(),
  proposalId: __t.u32(),
  memberName: __t.string(),
  acceptedAt: __t.timestamp(),
});
export type MyRoomAcceptance = __Infer<typeof MyRoomAcceptance>;

export const MyRoomChat = __t.object("MyRoomChat", {
  id: __t.u64(),
  roomId: __t.u32(),
  senderIdentity: __t.identity(),
  senderName: __t.string(),
  isBot: __t.bool(),
  body: __t.string(),
  kind: __t.string(),
  payloadJson: __t.string(),
  sentAt: __t.timestamp(),
});
export type MyRoomChat = __Infer<typeof MyRoomChat>;

export const MyRoomChoice = __t.object("MyRoomChoice", {
  choiceId: __t.u32(),
  roomId: __t.u32(),
  label: __t.string(),
  price: __t.option(__t.u32()),
  minPeople: __t.u32(),
  sortOrder: __t.u32(),
});
export type MyRoomChoice = __Infer<typeof MyRoomChoice>;

export const MyRoomDecision = __t.object("MyRoomDecision", {
  decisionId: __t.u32(),
  roomId: __t.u32(),
  choiceId: __t.u32(),
  lockedAt: __t.timestamp(),
  decisionDurationSeconds: __t.u64(),
  eligibleAcceptanceCount: __t.u32(),
});
export type MyRoomDecision = __Infer<typeof MyRoomDecision>;

export const MyRoomLocation = __t.object("MyRoomLocation", {
  id: __t.u64(),
  roomId: __t.u32(),
  friendId: __t.u32(),
  lat: __t.f64(),
  lng: __t.f64(),
  submittedAt: __t.timestamp(),
});
export type MyRoomLocation = __Infer<typeof MyRoomLocation>;

export const MyRoomMember = __t.object("MyRoomMember", {
  membershipId: __t.u32(),
  roomId: __t.u32(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
  get role() {
    return RoomMembershipRole;
  },
});
export type MyRoomMember = __Infer<typeof MyRoomMember>;

export const MyRoomMetrics = __t.object("MyRoomMetrics", {
  roomId: __t.u32(),
  decisionCount: __t.u32(),
  totalDecisionSeconds: __t.u64(),
  latestLockedAt: __t.option(__t.timestamp()),
});
export type MyRoomMetrics = __Infer<typeof MyRoomMetrics>;

export const MyRoomPreference = __t.object("MyRoomPreference", {
  id: __t.u64(),
  roomId: __t.u32(),
  friendId: __t.u32(),
  friendName: __t.string(),
  statement: __t.string(),
  category: __t.string(),
  sourceMessageId: __t.u64(),
  recordedAt: __t.timestamp(),
});
export type MyRoomPreference = __Infer<typeof MyRoomPreference>;

export const MyRoomProposal = __t.object("MyRoomProposal", {
  proposalId: __t.u32(),
  roomId: __t.u32(),
  choiceId: __t.u32(),
  proposerName: __t.string(),
  get status() {
    return ProposalStatus;
  },
  createdAt: __t.timestamp(),
});
export type MyRoomProposal = __Infer<typeof MyRoomProposal>;

export const MyRoomSchedule = __t.object("MyRoomSchedule", {
  roomId: __t.u32(),
  startsAt: __t.timestamp(),
  endsAt: __t.timestamp(),
  timezone: __t.string(),
});
export type MyRoomSchedule = __Infer<typeof MyRoomSchedule>;

export const MyRoomVote = __t.object("MyRoomVote", {
  voteId: __t.u32(),
  roomId: __t.u32(),
  choiceId: __t.u32(),
  memberName: __t.string(),
  get state() {
    return AnswerState;
  },
  maxPrice: __t.option(__t.u32()),
});
export type MyRoomVote = __Infer<typeof MyRoomVote>;

export const Plan = __t.object("Plan", {
  id: __t.u32(),
  shareCode: __t.string(),
  title: __t.string(),
  dateLabel: __t.string(),
  get status() {
    return PlanStatus;
  },
  lockedActivityId: __t.option(__t.u32()),
  version: __t.u64(),
  scheduledAt: __t.option(__t.timestamp()),
});
export type Plan = __Infer<typeof Plan>;

// The tagged union or sum type for the algebraic type `PlanStatus`.
export const PlanStatus = __t.enum("PlanStatus", {
  Open: __t.unit(),
  Locked: __t.unit(),
});
export type PlanStatus = __Infer<typeof PlanStatus>;

export const PrivateRoom = __t.object("PrivateRoom", {
  id: __t.u32(),
  publicRoomId: __t.string(),
  creatorIdentity: __t.identity(),
  title: __t.string(),
  createdAt: __t.timestamp(),
  get status() {
    return PrivateRoomStatus;
  },
  lockedChoiceId: __t.option(__t.u32()),
});
export type PrivateRoom = __Infer<typeof PrivateRoom>;

export const PrivateRoomChoiceInput = __t.object("PrivateRoomChoiceInput", {
  label: __t.string(),
  price: __t.option(__t.u32()),
  minPeople: __t.u32(),
});
export type PrivateRoomChoiceInput = __Infer<typeof PrivateRoomChoiceInput>;

// The tagged union or sum type for the algebraic type `PrivateRoomStatus`.
export const PrivateRoomStatus = __t.enum("PrivateRoomStatus", {
  Open: __t.unit(),
  Locked: __t.unit(),
});
export type PrivateRoomStatus = __Infer<typeof PrivateRoomStatus>;

export const Proposal = __t.object("Proposal", {
  id: __t.u32(),
  planId: __t.u32(),
  activityId: __t.u32(),
  proposedBy: __t.u32(),
  get status() {
    return ProposalStatus;
  },
  createdAt: __t.timestamp(),
});
export type Proposal = __Infer<typeof Proposal>;

// The tagged union or sum type for the algebraic type `ProposalStatus`.
export const ProposalStatus = __t.enum("ProposalStatus", {
  Pending: __t.unit(),
  Locked: __t.unit(),
  Cancelled: __t.unit(),
  Reopened: __t.unit(),
});
export type ProposalStatus = __Infer<typeof ProposalStatus>;

export const RoomAcceptance = __t.object("RoomAcceptance", {
  id: __t.u32(),
  roomId: __t.u32(),
  proposalId: __t.u32(),
  memberIdentity: __t.identity(),
  acceptedAt: __t.timestamp(),
  acceptanceKey: __t.string(),
});
export type RoomAcceptance = __Infer<typeof RoomAcceptance>;

export const RoomChoice = __t.object("RoomChoice", {
  id: __t.u32(),
  roomId: __t.u32(),
  label: __t.string(),
  price: __t.option(__t.u32()),
  minPeople: __t.u32(),
  sortOrder: __t.u32(),
});
export type RoomChoice = __Infer<typeof RoomChoice>;

export const RoomDecision = __t.object("RoomDecision", {
  id: __t.u32(),
  roomId: __t.u32(),
  choiceId: __t.u32(),
  lockedAt: __t.timestamp(),
  decisionDurationSeconds: __t.u64(),
  eligibleAcceptanceCount: __t.u32(),
});
export type RoomDecision = __Infer<typeof RoomDecision>;

export const RoomInvite = __t.object("RoomInvite", {
  id: __t.u32(),
  roomId: __t.u32(),
  tokenHash: __t.string(),
  expiresAt: __t.option(__t.timestamp()),
  maxUses: __t.option(__t.u32()),
  uses: __t.u32(),
  revokedAt: __t.option(__t.timestamp()),
});
export type RoomInvite = __Infer<typeof RoomInvite>;

export const RoomMembership = __t.object("RoomMembership", {
  id: __t.u32(),
  roomId: __t.u32(),
  identity: __t.identity(),
  membershipKey: __t.string(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
  get role() {
    return RoomMembershipRole;
  },
  leftAt: __t.option(__t.timestamp()),
});
export type RoomMembership = __Infer<typeof RoomMembership>;

// The tagged union or sum type for the algebraic type `RoomMembershipRole`.
export const RoomMembershipRole = __t.enum("RoomMembershipRole", {
  Creator: __t.unit(),
  Member: __t.unit(),
});
export type RoomMembershipRole = __Infer<typeof RoomMembershipRole>;

export const RoomMetrics = __t.object("RoomMetrics", {
  roomId: __t.u32(),
  decisionCount: __t.u32(),
  totalDecisionSeconds: __t.u64(),
  latestLockedAt: __t.option(__t.timestamp()),
});
export type RoomMetrics = __Infer<typeof RoomMetrics>;

export const RoomProposal = __t.object("RoomProposal", {
  id: __t.u32(),
  roomId: __t.u32(),
  choiceId: __t.u32(),
  proposerIdentity: __t.identity(),
  get status() {
    return ProposalStatus;
  },
  createdAt: __t.timestamp(),
});
export type RoomProposal = __Infer<typeof RoomProposal>;

export const RoomPublicShare = __t.object("RoomPublicShare", {
  roomId: __t.u32(),
  showSchedule: __t.bool(),
});
export type RoomPublicShare = __Infer<typeof RoomPublicShare>;

export const RoomSchedule = __t.object("RoomSchedule", {
  id: __t.u32(),
  roomId: __t.u32(),
  startsAt: __t.timestamp(),
  endsAt: __t.timestamp(),
  timezone: __t.string(),
});
export type RoomSchedule = __Infer<typeof RoomSchedule>;

export const RoomVote = __t.object("RoomVote", {
  id: __t.u32(),
  roomId: __t.u32(),
  choiceId: __t.u32(),
  memberIdentity: __t.identity(),
  get state() {
    return AnswerState;
  },
  maxPrice: __t.option(__t.u32()),
  voteKey: __t.string(),
});
export type RoomVote = __Infer<typeof RoomVote>;

export const SharedRoomStory = __t.object("SharedRoomStory", {
  id: __t.string(),
  title: __t.string(),
  get status() {
    return PrivateRoomStatus;
  },
  choiceLabels: __t.array(__t.string()),
  selectedChoiceLabel: __t.option(__t.string()),
  decisionCount: __t.u32(),
  publishedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  startsAt: __t.option(__t.timestamp()),
  timezone: __t.option(__t.string()),
});
export type SharedRoomStory = __Infer<typeof SharedRoomStory>;
