// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Acceptance = __t.object("Acceptance", {
  id: __t.u32(),
  planId: __t.u32(),
  proposalId: __t.u32(),
  friendId: __t.u32(),
  acceptedAt: __t.timestamp(),
  acceptanceKey: __t.string(),
});
export type Acceptance = __Infer<typeof Acceptance>;

export const Activity = __t.object("Activity", {
  id: __t.u32(),
  planId: __t.u32(),
  name: __t.string(),
  price: __t.u32(),
  minPeople: __t.u32(),
});
export type Activity = __Infer<typeof Activity>;

export const Answer = __t.object("Answer", {
  id: __t.u32(),
  planId: __t.u32(),
  friendId: __t.u32(),
  activityId: __t.u32(),
  get state() {
    return AnswerState;
  },
  maxPrice: __t.option(__t.u32()),
  answerKey: __t.string(),
});
export type Answer = __Infer<typeof Answer>;

// The tagged union or sum type for the algebraic type `AnswerState`.
export const AnswerState = __t.enum("AnswerState", {
  In: __t.unit(),
  Out: __t.unit(),
  Conditional: __t.unit(),
});
export type AnswerState = __Infer<typeof AnswerState>;

export const EventLog = __t.object("EventLog", {
  id: __t.u64(),
  planId: __t.u32(),
  kind: __t.string(),
  friendId: __t.option(__t.u32()),
  activityId: __t.option(__t.u32()),
  message: __t.string(),
  at: __t.timestamp(),
});
export type EventLog = __Infer<typeof EventLog>;

export const Friend = __t.object("Friend", {
  id: __t.u32(),
  planId: __t.u32(),
  identity: __t.identity(),
  friendKey: __t.string(),
  name: __t.string(),
  online: __t.bool(),
  joinedAt: __t.timestamp(),
  droppedAt: __t.option(__t.timestamp()),
});
export type Friend = __Infer<typeof Friend>;

export const Plan = __t.object("Plan", {
  id: __t.u32(),
  shareCode: __t.string(),
  title: __t.string(),
  dateLabel: __t.string(),
  get status() {
    return PlanStatus;
  },
  lockedActivityId: __t.option(__t.u32()),
  version: __t.u64(),
});
export type Plan = __Infer<typeof Plan>;

// The tagged union or sum type for the algebraic type `PlanStatus`.
export const PlanStatus = __t.enum("PlanStatus", {
  Open: __t.unit(),
  Locked: __t.unit(),
});
export type PlanStatus = __Infer<typeof PlanStatus>;

export const Proposal = __t.object("Proposal", {
  id: __t.u32(),
  planId: __t.u32(),
  activityId: __t.u32(),
  proposedBy: __t.u32(),
  get status() {
    return ProposalStatus;
  },
  createdAt: __t.timestamp(),
});
export type Proposal = __Infer<typeof Proposal>;

// The tagged union or sum type for the algebraic type `ProposalStatus`.
export const ProposalStatus = __t.enum("ProposalStatus", {
  Pending: __t.unit(),
  Locked: __t.unit(),
  Cancelled: __t.unit(),
  Reopened: __t.unit(),
});
export type ProposalStatus = __Infer<typeof ProposalStatus>;
